# Generated by Django 3.2.5 on 2021-10-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('rate', models.IntegerField(default=0)),
                ('room_size', models.CharField(max_length=50)),
                ('descripttion', models.CharField(max_length=255)),
                ('seller_id', models.CharField(default='null', max_length=20)),
            ],
        ),
    ]
