# Generated by Django 3.2.5 on 2021-10-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='descripttion',
            new_name='description',
        ),
    ]
