# Generated by Django 3.2.5 on 2021-10-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_descripttion_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='area',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='room',
            name='furnishing',
            field=models.CharField(default='null', max_length=25),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='parking',
            field=models.CharField(default='null', max_length=25),
        ),
    ]
